import { Bell, ClipboardCheck, FileWarning, Inbox, UserRound } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

const statusMeta = { open: { label: "待處理", className: "status-warning" }, in_progress: { label: "處理中", className: "status-info" }, completed: { label: "已完成", className: "status-success" }, cancelled: { label: "已取消", className: "status-neutral" } } as const;

export default function DataCompletionInbox() {
  const [, setLocation] = useLocation();
  const { data: tasks, isLoading: tasksLoading } = trpc.aiGovernance.myDataCompletionTasks.useQuery();
  const { data: notifications } = trpc.aiGovernance.myTaskNotifications.useQuery();
  return <div className="space-y-6 p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">我的工作／資料治理</p><h1 className="text-2xl font-bold">補件任務與通知</h1><p className="mt-1 text-sm text-muted-foreground">此處列出指派給你的高頻資料缺口補件任務；完成補件後請回到對應模組更新資料。</p></div><Button variant="outline" onClick={() => setLocation("/")}>返回首頁</Button></div>
    <div className="grid gap-4 lg:grid-cols-[1.3fr_0.7fr]"><Card className="status-info border"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ClipboardCheck className="status-icon h-4 w-4" />我的補件任務</CardTitle></CardHeader><CardContent className="space-y-3">{tasksLoading ? <p className="status-detail py-8 text-center text-sm">載入中…</p> : !tasks?.length ? <div className="py-10 text-center"><Inbox className="status-detail mx-auto h-9 w-9" /><p className="status-detail mt-2 text-sm">目前沒有指派給你的補件任務。</p></div> : tasks.map((task) => { const meta = statusMeta[task.status]; return <div key={task.id} className="rounded-lg border border-current/20 bg-black/5 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{task.title}</p><p className="status-detail mt-1 text-sm whitespace-pre-line">{task.description}</p></div><span className={`rounded-full border px-2 py-1 text-xs ${meta.className}`}>{meta.label}</span></div><div className="status-detail mt-3 grid gap-2 text-xs sm:grid-cols-3"><span><UserRound className="mr-1 inline h-3.5 w-3.5" />建議提供者：{task.recommendedProvider}</span><span><FileWarning className="mr-1 inline h-3.5 w-3.5" />出現 {task.frequencyCount} 次</span><span>建立：{new Date(task.createdAt).toLocaleDateString("zh-TW")}</span></div></div>; })}</CardContent></Card><Card className="status-neutral border"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Bell className="status-icon h-4 w-4" />系統通知</CardTitle></CardHeader><CardContent className="space-y-3">{!notifications?.length ? <p className="status-detail py-8 text-center text-sm">目前沒有新通知。</p> : notifications.map((notification) => <div key={notification.id} className="rounded-lg border border-current/20 bg-black/5 p-3"><p className="text-sm font-medium">{notification.title}</p><p className="status-detail mt-1 text-xs">{notification.content}</p><p className="status-detail mt-2 text-[10px]">{new Date(notification.createdAt).toLocaleString("zh-TW")}</p></div>)}</CardContent></Card></div>
  </div>;
}
