import { useMemo } from "react";
import { Route, Switch, useLocation, useParams } from "wouter";
import { Activity, ArrowLeft, BarChart3, Brain, CheckCircle2, ChevronRight, ClipboardCheck, Factory, Gauge, ListChecks, Menu, Monitor, MoreHorizontal, Settings2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import TimeStudy from "@/pages/TimeStudy";
import AISuggestions from "@/pages/AISuggestions";
import { DESKTOP_ENTRY_PATH, MOBILE_ENTRY_PATH } from "../../../shared/mobileEntry";

const mobileTitle = (path: string) => path.includes("/time-study") ? "工時觀測" : path.includes("/ai") ? "AI 分析" : path.includes("/balance") ? "平衡摘要" : path.includes("/lines/") ? "工站概覽" : path.includes("/lines") ? "產線" : path.includes("/tasks") ? "任務" : path.includes("/more") ? "更多" : "現場首頁";

export default function MobileFieldApp() {
  const [location, setLocation] = useLocation();
  const { user } = useAuth();
  const title = mobileTitle(location);
  return <div className="min-h-dvh bg-background text-foreground"><header className="sticky top-0 z-30 flex min-h-14 items-center gap-3 border-b border-border/80 bg-background/95 px-4 backdrop-blur"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-400/15"><Activity className="h-4 w-4 text-cyan-400" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-cyan-400">PLA Field</p><p className="truncate text-sm font-semibold">{title}</p></div><button className="flex h-10 items-center gap-1.5 rounded-lg border border-border px-2.5 text-xs font-medium text-muted-foreground" onClick={() => setLocation(DESKTOP_ENTRY_PATH)} aria-label="切換至桌面管理版"><Monitor className="h-4 w-4" /><span>桌面</span></button><button className="flex h-10 w-10 items-center justify-center rounded-lg border border-border text-muted-foreground" onClick={() => setLocation(`${MOBILE_ENTRY_PATH}/more`)} aria-label="開啟更多功能"><Menu className="h-5 w-5" /></button></header><main className="mx-auto max-w-lg px-4 pb-[calc(5.5rem+env(safe-area-inset-bottom))] pt-4"><Switch><Route path={MOBILE_ENTRY_PATH} component={MobileFieldHome} /><Route path={`${MOBILE_ENTRY_PATH}/lines`} component={MobileLineList} /><Route path={`${MOBILE_ENTRY_PATH}/lines/:id/time-study`}><TimeStudy mobileMode /></Route><Route path={`${MOBILE_ENTRY_PATH}/lines/:id/balance`} component={MobileBalance} /><Route path={`${MOBILE_ENTRY_PATH}/lines/:id/ai`}><AISuggestions mobileMode /></Route><Route path={`${MOBILE_ENTRY_PATH}/lines/:id`} component={MobileLineOverview} /><Route path={`${MOBILE_ENTRY_PATH}/tasks`} component={MobileTasks} /><Route path={`${MOBILE_ENTRY_PATH}/more`} component={MobileMore} /><Route component={MobileFieldHome} /></Switch></main><MobileFieldBottomNavigation location={location} navigate={setLocation} userName={user?.name} /></div>;
}

function MobileFieldBottomNavigation({ location, navigate, userName }: { location: string; navigate: (path: string) => void; userName?: string | null }) {
  const items = [{ label: "首頁", path: "/mobile", icon: Activity }, { label: "產線", path: "/mobile/lines", icon: Factory }, { label: "任務", path: "/mobile/tasks", icon: ListChecks }, { label: "更多", path: "/mobile/more", icon: MoreHorizontal }];
  return <nav className="fixed inset-x-0 bottom-0 z-30 flex border-t border-border bg-background/95 px-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] pt-2 shadow-[0_-8px_20px_rgba(0,0,0,.14)] backdrop-blur" aria-label="手機現場作業導覽">{items.map((item) => { const Icon = item.icon; const active = item.path === "/mobile" ? location === "/mobile" : location.startsWith(item.path); return <button key={item.path} onClick={() => navigate(item.path)} className={`flex min-h-14 flex-1 flex-col items-center justify-center gap-1 rounded-lg text-[11px] font-medium ${active ? "bg-primary/12 text-primary" : "text-muted-foreground"}`} aria-current={active ? "page" : undefined}><Icon className="h-5 w-5" /><span>{item.label}</span></button>; })}</nav>;
}

function MobileFieldHome() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const { data: lines = [] } = trpc.productionLine.list.useQuery();
  const { data: latest = [] } = trpc.snapshot.getAllLinesLatestByDate.useQuery();
  const activeLines = lines.filter((line: any) => line.status === "active");
  const focus = (latest as any[]).filter((item) => item.snapshot).sort((a, b) => Number(a.snapshot.balanceRate) - Number(b.snapshot.balanceRate))[0];
  const focusLine = focus ? { id: focus.lineId, name: focus.lineName, balanceRate: Number(focus.snapshot.balanceRate) } : activeLines[0];
  const focusBalanceRate = (focusLine as any)?.balanceRate;
  return <div className="space-y-5"><section className="rounded-2xl border border-cyan-400/20 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.16),transparent_42%),linear-gradient(135deg,rgba(15,23,42,.98),rgba(8,32,44,.96))] p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300">現場作業入口</p><h1 className="mt-2 text-2xl font-bold text-white">{user?.name ? `${user.name}，開始作業` : "開始現場作業"}</h1><p className="mt-2 text-sm leading-6 text-slate-300">此入口僅提供行動現場流程；完整管理、配置與治理功能請使用桌面版。</p>{focusLine ? <button onClick={() => setLocation(`/mobile/lines/${focusLine.id}`)} className="mt-4 flex w-full items-center justify-between rounded-xl border border-white/10 bg-black/15 p-4 text-left"><span><small className="text-slate-300">優先產線</small><b className="mt-1 block text-white">{focusLine.name}</b>{focusBalanceRate !== undefined && <small className="mt-1 block text-cyan-200">平衡率 {Number(focusBalanceRate).toFixed(1)}%</small>}</span><ChevronRight className="h-5 w-5 text-cyan-300" /></button> : <Button className="mt-4 w-full" onClick={() => setLocation("/mobile/lines")}>選擇產線</Button>}</section><div className="grid grid-cols-2 gap-3"><Metric label="運行中產線" value={`${activeLines.length} 條`} color="text-cyan-400" /><Metric label="可用現場流程" value="4 項" color="text-emerald-400" /></div><section><h2 className="font-semibold">快速開始</h2><div className="mt-3 grid grid-cols-2 gap-3">{[{ label: "工時觀測", icon: Activity, path: focusLine ? `/mobile/lines/${focusLine.id}/time-study` : "/mobile/lines", tone: "text-cyan-400" }, { label: "工站查閱", icon: Factory, path: focusLine ? `/mobile/lines/${focusLine.id}` : "/mobile/lines", tone: "text-emerald-400" }, { label: "平衡摘要", icon: BarChart3, path: focusLine ? `/mobile/lines/${focusLine.id}/balance` : "/mobile/lines", tone: "text-violet-400" }, { label: "AI 分析", icon: Brain, path: focusLine ? `/mobile/lines/${focusLine.id}/ai` : "/mobile/lines", tone: "text-amber-400" }].map((item) => <button key={item.label} onClick={() => setLocation(item.path)} className="min-h-28 rounded-xl border border-border bg-card p-4 text-left active:scale-[0.98]"><item.icon className={`h-5 w-5 ${item.tone}`} /><b className="mt-3 block text-sm">{item.label}</b></button>)}</div></section></div>;
}

function MobileLineList() {
  const [, setLocation] = useLocation();
  const { data: lines = [], isLoading } = trpc.productionLine.list.useQuery();
  return <div className="space-y-3"><div><h1 className="text-xl font-bold">選擇產線</h1><p className="mt-1 text-sm text-muted-foreground">選取後進入工站、工時與分析現場流程。</p></div>{isLoading ? <p className="py-12 text-center text-sm text-muted-foreground">載入產線中…</p> : lines.length === 0 ? <EmptyMobile title="尚無產線資料" detail="請先於桌面管理版建立產線與工站。" /> : lines.map((line: any) => <button key={line.id} onClick={() => setLocation(`/mobile/lines/${line.id}`)} className="flex w-full items-center gap-3 rounded-xl border border-border bg-card p-4 text-left active:scale-[0.99]"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10"><Factory className="h-5 w-5 text-primary" /></div><span className="min-w-0 flex-1"><b className="block truncate">{line.name}</b><small className="mt-1 block text-muted-foreground">{line.targetCycleTime ? `Takt ${Number(line.targetCycleTime).toFixed(1)} 秒` : "尚未設定 Takt"}</small></span><ChevronRight className="h-5 w-5 text-muted-foreground" /></button>)}</div>;
}

function MobileLineOverview() {
  const { id } = useParams<{ id: string }>();
  const lineId = Number(id ?? 0); const [, setLocation] = useLocation();
  const { data: line } = trpc.productionLine.getById.useQuery({ id: lineId });
  const { data: workstations = [] } = trpc.workstation.listByLine.useQuery({ productionLineId: lineId });
  const { data: standards = [] } = trpc.timeStudy.publishedByLine.useQuery({ productionLineId: lineId });
  const standardMap = new Map(standards.map((study) => [study.workstationId, study]));
  return <div className="space-y-4"><BackButton onClick={() => setLocation("/mobile/lines")} label="所有產線" /><section><h1 className="text-xl font-bold">{line?.name ?? "產線"}</h1><p className="mt-1 text-sm text-muted-foreground">{workstations.length} 個工站 · {line?.targetCycleTime ? `Takt ${Number(line.targetCycleTime).toFixed(1)} 秒` : "未設定 Takt"}</p></section><div className="grid grid-cols-2 gap-3"><ActionButton icon={Activity} label="工時觀測" onClick={() => setLocation(`/mobile/lines/${lineId}/time-study`)} /><ActionButton icon={BarChart3} label="平衡摘要" onClick={() => setLocation(`/mobile/lines/${lineId}/balance`)} /><ActionButton icon={Brain} label="AI 分析" onClick={() => setLocation(`/mobile/lines/${lineId}/ai`)} /></div><section><h2 className="font-semibold">工站概覽</h2><div className="mt-3 space-y-2">{workstations.map((station) => { const standard = standardMap.get(station.id); return <Card key={station.id}><CardContent className="flex items-center justify-between p-4"><span><b className="block text-sm">{station.sequenceOrder}. {station.name}</b><small className="mt-1 block text-muted-foreground">CT {Number(station.cycleTime).toFixed(2)} 秒 · {Number(station.manpower).toFixed(1)} 人</small></span><span className="text-right"><small className="block text-muted-foreground">標準工時</small><b className="text-sm text-emerald-400">{standard?.standardTime ? `${Number(standard.standardTime).toFixed(2)} 秒` : "—"}</b></span></CardContent></Card>; })}{workstations.length === 0 && <EmptyMobile title="尚無工站" detail="請於桌面管理版建立工站資料。" />}</div></section></div>;
}

function MobileBalance() {
  const { id } = useParams<{ id: string }>(); const lineId = Number(id ?? 0); const [, setLocation] = useLocation();
  const { data: line } = trpc.productionLine.getById.useQuery({ id: lineId }); const { data: workstations = [] } = trpc.workstation.listByLine.useQuery({ productionLineId: lineId });
  const summary = useMemo(() => { const times = workstations.map((station) => Number(station.cycleTime)).filter((value) => value > 0); if (!times.length) return null; const max = Math.max(...times); const total = times.reduce((sum, value) => sum + value, 0); return { max, average: total / times.length, balance: total / (max * times.length), bottleneck: workstations.find((station) => Number(station.cycleTime) === max) }; }, [workstations]);
  return <div className="space-y-4"><BackButton onClick={() => setLocation(`/mobile/lines/${lineId}`)} label="返回產線" /><h1 className="text-xl font-bold">{line?.name ?? "產線"} 平衡摘要</h1>{!summary ? <EmptyMobile title="尚無可分析工站" detail="請先建立工站與週期時間。" /> : <><div className="grid grid-cols-2 gap-3"><Metric label="平衡率" value={`${(summary.balance * 100).toFixed(1)}%`} color="text-emerald-400" /><Metric label="瓶頸 CT" value={`${summary.max.toFixed(2)} 秒`} color="text-amber-400" /><Metric label="平均 CT" value={`${summary.average.toFixed(2)} 秒`} color="text-cyan-400" /><Metric label="瓶頸工站" value={summary.bottleneck?.name ?? "—"} color="text-violet-400" /></div><Button className="min-h-11 w-full" onClick={() => setLocation(`/mobile/lines/${lineId}/ai`)}><Brain className="mr-2 h-4 w-4" />以此產線進行 AI 分析</Button></>}</div>;
}

function MobileTasks() { const [, setLocation] = useLocation(); return <div className="space-y-4"><h1 className="text-xl font-bold">我的補件任務</h1><Card><CardContent className="p-5"><ClipboardCheck className="h-8 w-8 text-violet-400" /><p className="mt-3 font-semibold">前往任務工作區</p><p className="mt-1 text-sm leading-6 text-muted-foreground">補件任務會依您的權限與指派狀態呈現。</p><Button className="mt-4 min-h-11 w-full" onClick={() => setLocation("/data-completion-inbox")}>開啟任務</Button></CardContent></Card></div>; }
function MobileMore() { const [, setLocation] = useLocation(); return <div className="space-y-4"><h1 className="text-xl font-bold">更多功能</h1><Card><CardContent className="space-y-3 p-5"><p className="text-sm text-muted-foreground">完整的產線設定、VSM、治理、使用者與權限管理保留於桌面管理版。</p><Button variant="outline" className="min-h-11 w-full" onClick={() => setLocation(DESKTOP_ENTRY_PATH)}><Settings2 className="mr-2 h-4 w-4" />開啟桌面管理版</Button></CardContent></Card></div>; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 truncate text-xl font-bold ${color}`}>{value}</p></CardContent></Card>; }
function ActionButton({ icon: Icon, label, onClick }: { icon: typeof Activity; label: string; onClick: () => void }) { return <button onClick={onClick} className="min-h-20 rounded-xl border border-border bg-card p-3 text-left active:scale-[0.98]"><Icon className="h-5 w-5 text-primary" /><span className="mt-2 block text-xs font-semibold">{label}</span></button>; }
function BackButton({ onClick, label }: { onClick: () => void; label: string }) { return <Button variant="ghost" className="-ml-2 min-h-10" onClick={onClick}><ArrowLeft className="mr-1 h-4 w-4" />{label}</Button>; }
function EmptyMobile({ title, detail }: { title: string; detail: string }) { return <div className="rounded-xl border border-dashed border-border p-8 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-muted-foreground/40" /><p className="mt-3 font-medium">{title}</p><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div>; }
